packages:
  base: !include base.yaml

esp32:
  board: m5stack-atoms3
  framework:
    type: esp-idf

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO2
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  stop_bits: 1